<?php


namespace App\Http\Validations\v1;


use Illuminate\Http\Request;
use LaravelSimpleBases\Http\Validations\BaseValidation;

class User2Validation extends BaseValidation
{

    public function validate(Request $request, $method)
    {

        $this->fieldsCreate = [     
            //Your validations here       
        ];

        parent::validate($request, $method); // TODO: Change the autogenerated stub
    }

}