<?php


namespace App\Http\Validations\v1;


use Illuminate\Http\Request;
use LaravelSimpleBases\Http\Validations\BaseValidation;

class UserValidation extends BaseValidation
{

    public function validate(Request $request, $method)
    {

        $this->fieldsCreate = [
            'name' => 'required'
        ];

        parent::validate($request, $method); // TODO: Change the autogenerated stub
    }

}
