<?php


namespace App\Services\v1;


use LaravelSimpleBases\Services\BaseService;

class UserService extends BaseService
{
    public function save($data)
    {
        $data['password'] = bcrypt('1234');
        return parent::save($data); // TODO: Change the autogenerated stub
    }
}
